server:
  port: 8040
  error:
    whitelabel:
      enabled: false

  servlet:
    context-path: /handson7

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/handson
    username: root
    password: admin
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/handson
#    username: handson
#    password: handson
  jpa:
    #show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.MariaDBDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect